package com.myspace.test_app;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Member implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id")
	private int id;
	@org.kie.api.definition.type.Label("bonus opt in")
	private boolean bonusOptIn;

	@org.kie.api.definition.type.Label(value = "Primary Member")
	private boolean primaryMember;

	public Member() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isBonusOptIn() {
		return this.bonusOptIn;
	}

	public void setBonusOptIn(boolean bonusOptIn) {
		this.bonusOptIn = bonusOptIn;
	}

	public boolean isPrimaryMember() {
		return this.primaryMember;
	}

	public void setPrimaryMember(boolean primaryMember) {
		this.primaryMember = primaryMember;
	}

	public Member(int id, boolean bonusOptIn, boolean primaryMember) {
		this.id = id;
		this.bonusOptIn = bonusOptIn;
		this.primaryMember = primaryMember;
	}

}