package com.myspace.test_app;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidationObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Member Limit Validation")
	private boolean memberLimitValidation;
	@org.kie.api.definition.type.Label(value = "Bonus Opt-in Validation")
	private boolean bonusOptinValidation;

	public ValidationObject() {
	}

	public boolean isMemberLimitValidation() {
		return this.memberLimitValidation;
	}

	public void setMemberLimitValidation(boolean memberLimitValidation) {
		this.memberLimitValidation = memberLimitValidation;
	}

	public boolean isBonusOptinValidation() {
		return this.bonusOptinValidation;
	}

	public void setBonusOptinValidation(boolean bonusOptinValidation) {
		this.bonusOptinValidation = bonusOptinValidation;
	}

	public ValidationObject(boolean memberLimitValidation,
			boolean bonusOptinValidation) {
		this.memberLimitValidation = memberLimitValidation;
		this.bonusOptinValidation = bonusOptinValidation;
	}

}